/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package odev1_part2;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
//Method swaps integers in arr in a and b index
    public static boolean swap(int[] arr, int a,int b){
        if(a==b)
            return false;
        int aIndex =-1;
        int bIndex=-1;
        for(int i=0;i<arr.length;i++){
            if(aIndex==-1)
                if(arr[i]==a)
                    aIndex=i;
            if(bIndex==-1)
                if(arr[i]==b)
                    bIndex=i;
        }
        if(aIndex==-1||bIndex==-1)
            return false;
        int tmp = arr[aIndex];
        arr[aIndex]=arr[bIndex];
        arr[bIndex]=tmp;
        return true;
    }
}
