/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package odev1_part2;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
 
     @Test
     public void testSame() {
        int[] array = new int[]{1,2,2,4};
        assertFalse(App.swap(array,2,2));
      }
 
     @Test
     public void testNotFoundFirst() {
        int[] array = new int[]{1,2,3,4};
        assertFalse(App.swap(array,2,5));
      }

      public void testNotFoundSecond() {
        int[] array = new int[]{1,2,3,4};
        assertFalse(App.swap(array,5,2));
      }
 
     @Test
     public void testEmptyArr() {
        int[] array = new int[3];
        assertFalse(App.swap(array,5,2));
      }

      public void testTrue() {
        int[] array = new int[]{1,2,3,4};
        assertTrue(App.swap(array,1,2));
      }
 
}
